= Table.RenameColumns(#"Remove region and country", {{"Region2","Region"}, {"Country2","Country"}})