= Table.RemoveColumns(#"Reordered Language Columns",{"Language"})