= Table.ReorderColumns(#"Add Language 24 Column",{"WWID", "Username", "Email", "Status", "First Name", "Last Name", "Phone Number", "Language", "Language 11", "Language 24", "Company Name", "Company Sector", "Region", "Country", "State", "City", "Business Area", "Business Subarea", "Job Group", "VIP", "Site Name", "Partner Company", "Sector", "Manager WWID", "Manager Email", "Manager Full Name", "Record Last Update Date"})