= Table.TransformColumns(#"Fill null Manager Email", {{"Manager Full Name", each if _ = null then "UNKNOWN" else if Text.Trim(_) = "" then "UNKNOWN" else _, type text}})