= Table.TransformColumnTypes(#"Removed Columns",{{"WWID", Int64.Type}})