= Table.AddColumn(#"Language Lowercase", "Language 11", each if [Language] = "eng" then "English" else if [Language] = "en" then "English" else if [Language] = "dut" then "Dutch" else if [Language] = "nl" then "Dutch" else if [Language] = "ger" then "German" else if [Language] = "ja" then "Japanese" else if [Language] = "jpn" then "Japanese" else if [Language] = "spa" then "Spanish" else if [Language] = "es" then "Spanish" else if [Language] = "por" then "Portuguese" else if [Language] = "pt" then "Portuguese" else if [Language] = "fre" then "French" else if [Language] = "fr" then "French" else if [Language] = "zh" then "Chinese" else if [Language] = "chi" then "Chinese" else if [Language] = "ita" then "Italian" else if [Language] = "it" then "Italian" else if [Language] = "ko" then "Korean" else if [Language] = "kor" then "Korean" else if [Language] = "rus" then "Russian" else "English")